In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings("ignore")
from mpl_toolkits import mplot3d

In [2]:
df = pd.read_csv('lr.csv')

In [3]:
m = len(df)

In [4]:
X = df[['Gender','Age','EstimatedSalary']]

In [5]:
y = df[['Purchased']]

In [6]:
X['Gender']=pd.get_dummies(X['Gender'])

In [7]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()

In [8]:
X['Age'] = sc.fit_transform(X['Age'].values.reshape(-1,1))

In [9]:
X['EstimatedSalary'] = sc.fit_transform(X['EstimatedSalary'].values.reshape(-1,1))

In [10]:
w = 0.07

In [11]:
X = X.values
y = y.values

In [12]:
y.shape

(400, 1)

In [13]:
z = np.sum(w*X, axis=1)

In [14]:
y_pred = (1 / (1 + np.exp(-z)))

In [15]:
y_pred.shape

(400,)

In [16]:
c = (-1/(m))*np.sum(y*np.log(y_pred) + (1 - y)*np.log(1 - y_pred)) 

In [17]:
alpha= 0.09

In [18]:
for i in range(1000):
    temp = w - alpha*(np.sum(y_pred - y)*X)
    w = temp
    y_pred = (1 / (1 + np.exp(-z)))
print(w)

[[ 7.00000000e-02 -5.71470187e+04 -7.11163071e+04]
 [ 7.00000000e-02 -9.71500438e+05 -8.88954013e+04]
 [-2.40017766e+06 -4.57176640e+05 -4.97814569e+05]
 ...
 [-2.40017766e+06 -1.82870677e+06 -8.88954013e+04]
 [ 7.00000000e-02 -1.02864753e+06 -3.20023627e+05]
 [-2.40017766e+06 -1.77155968e+06 -3.73360910e+05]]


In [19]:
y_pred.shape

(400,)

In [20]:
y_final = list(map(lambda num:0 if num < 0.54 else 1, y_pred))

In [21]:
from sklearn.metrics import accuracy_score
accuracy_score(y_final,y)

0.725

#### Sklearn

In [22]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [23]:
lr.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [24]:
y_pred = lr.predict(X)

In [25]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_pred,y)

In [26]:
score

0.825

In [36]:
s = X[Gender]

NameError: name 'Gender' is not defined

In [31]:
plt.scatter(X['Salary'],y_pred)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices